import 'package:cloud_firestore/cloud_firestore.dart';

class MockData {
  static DateTime nowRel(int days, {int hours = 0, int minutes = 0}) {
    final now = DateTime.now();
    return DateTime(
      now.year,
      now.month,
      now.day,
    ).add(Duration(days: days, hours: hours, minutes: minutes));
  }

  static List<Map<String, dynamic>> get events => [
    {
      'id': 'evt_1',
      'title': 'Global Revival 2026',
      'shortDescription': 'A 40-day global prayer and fasting movement.',
      'fullDescription':
          'Join thousands around the world for a season of spiritual renewal and intense seeking of God\'s face.',
      'objectiveStatement': 'To catalyze a global movement of prayer.',
      'coverImageUrl':
          'https://images.unsplash.com/photo-1544427928-c49dd2492d26?q=80&w=2000&auto=format&fit=crop',
      'thematicVerseSummary': '2 Chronicles 7:14',
      'startDate': nowRel(-5),
      'endDate': nowRel(35),
      'visibility': 'public',
      'status': 'active',
      'creatorId': 'user_offline', // JOINED BY DEFAULT
      'createdAt': nowRel(-10),
      'numberOfRooms': 12,
      'numberOfActivities': 40,
    },
    {
      'id': 'evt_2',
      'title': 'The Wisdom Path',
      'shortDescription': 'Study the book of Proverbs in depth.',
      'fullDescription':
          'Exploring the practical wisdom of Solomon for modern life.',
      'objectiveStatement': 'To grow in divine wisdom.',
      'coverImageUrl':
          'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?q=80&w=2000&auto=format&fit=crop',
      'thematicVerseSummary': 'Proverbs 4:7',
      'startDate': nowRel(2),
      'endDate': nowRel(12),
      'visibility': 'public',
      'status': 'active',
      'creatorId': 'user_offline', // JOINED BY DEFAULT
      'createdAt': nowRel(-2),
      'numberOfRooms': 5,
      'numberOfActivities': 10,
    },
    {
      'id': 'evt_3',
      'title': 'The Call to Missions',
      'shortDescription': 'Annual summit for global missions.',
      'fullDescription':
          'A gathering of ministries and individuals dedicated to the Great Commission.',
      'objectiveStatement': 'To inspire and equip for global outreach.',
      'coverImageUrl':
          'https://images.unsplash.com/photo-1493612276216-ee3925520721?q=80&w=2000&auto=format&fit=crop',
      'thematicVerseSummary': 'Matthew 28:19',
      'startDate': nowRel(15),
      'endDate': nowRel(20),
      'visibility': 'public',
      'status': 'active',
      'creatorId': 'admin_2',
      'createdAt': nowRel(-5),
      'numberOfRooms': 3,
      'numberOfActivities': 15,
    },
    {
      'id': 'evt_4',
      'title': 'Sacred Songs & Silence',
      'shortDescription': 'A retreat for worship and contemplation.',
      'fullDescription':
          'Unplug from the noise and tune into the voice of the Spirit.',
      'objectiveStatement': 'To deepen personal intimacy with God.',
      'coverImageUrl':
          'https://images.unsplash.com/photo-1507692049790-de58290a4334?q=80&w=2000&auto=format&fit=crop',
      'thematicVerseSummary': 'Psalm 46:10',
      'startDate': nowRel(30),
      'endDate': nowRel(35),
      'visibility': 'public',
      'status': 'active',
      'creatorId': 'admin_3',
      'createdAt': nowRel(-7),
      'numberOfRooms': 2,
      'numberOfActivities': 8,
    },
    {
      'id': 'evt_5',
      'title': 'Youth Awakening',
      'shortDescription': 'Igniting the next generation for Christ.',
      'fullDescription':
          'A vibrant gathering of young believers for worship and ministry.',
      'objectiveStatement': 'To empower youth for spiritual leadership.',
      'coverImageUrl':
          'https://images.unsplash.com/photo-1523580494863-6f30312248fd?q=80&w=2000&auto=format&fit=crop',
      'thematicVerseSummary': '1 Timothy 4:12',
      'startDate': nowRel(45),
      'endDate': nowRel(48),
      'visibility': 'public',
      'status': 'active',
      'creatorId': 'admin_4',
      'createdAt': nowRel(-10),
      'numberOfRooms': 4,
      'numberOfActivities': 20,
    },
  ];

  static List<Map<String, dynamic>> get rooms => [
    {
      'id': 'room_1',
      'eventId': 'evt_1',
      'title': 'Midnight Intercession',
      'description': 'A room dedicated to midnight prayer.',
      'objective': 'Pray for the nations at the midnight hour.',
      'roomType': 'prayer_fasting',
      'visibility': 'public',
      'status': 'open',
      'startDate': nowRel(-5),
      'endDate': nowRel(35),
      'creatorId': 'user_offline', // JOINED BY DEFAULT
      'createdAt': nowRel(-6),
      'coverImageUrl':
          'https://images.unsplash.com/photo-1512411513220-40e8549f646b?q=80&w=2000&auto=format&fit=crop',
    },
    {
      'id': 'room_2',
      'eventId': 'evt_1',
      'title': 'Daily Rhema Exploration',
      'description': 'Daily study of the Word.',
      'objective': 'Develop a consistent habit of hearing God.',
      'roomType': 'bible_study',
      'visibility': 'public',
      'status': 'open',
      'startDate': nowRel(-5),
      'endDate': nowRel(35),
      'creatorId': 'user_offline', // JOINED BY DEFAULT
      'createdAt': nowRel(-6),
      'coverImageUrl':
          'https://images.unsplash.com/photo-1504052434569-70ad531eec4a?q=80&w=2000&auto=format&fit=crop',
    },
    {
      'id': 'room_3',
      'eventId': 'evt_3',
      'title': 'Missions Planning Hub',
      'description': 'Stratigic planning for field missionaries.',
      'objective': 'Review 2026 reach goals.',
      'roomType': 'retreat',
      'visibility': 'public',
      'status': 'open',
      'startDate': nowRel(15),
      'endDate': nowRel(20),
      'creatorId': 'admin_2',
      'createdAt': nowRel(-5),
      'coverImageUrl':
          'https://images.unsplash.com/photo-1516733725897-1aa73b87c8e8?q=80&w=2000&auto=format&fit=crop',
    },
    {
      'id': 'room_4',
      'eventId': null,
      'title': 'The Silence of the Lamb',
      'description': 'A contemplative space for prayer.',
      'objective': 'Internal peace and spiritual stillness.',
      'roomType': 'retreat',
      'visibility': 'public',
      'status': 'open',
      'startDate': nowRel(1),
      'endDate': nowRel(10),
      'creatorId': 'admin_3',
      'createdAt': nowRel(-2),
      'coverImageUrl':
          'https://images.unsplash.com/photo-1499209974431-9dac3adaf471?q=80&w=2000&auto=format&fit=crop',
    },
    {
      'id': 'room_5',
      'eventId': 'evt_2',
      'title': 'Wisdom Circle: Solomon\'s Path',
      'description': 'Diving deeper into the wisdom literature.',
      'objective': 'Practical application of Proverbs.',
      'roomType': 'book_study',
      'visibility': 'public',
      'status': 'open',
      'startDate': nowRel(2),
      'endDate': nowRel(12),
      'creatorId': 'admin_1',
      'createdAt': nowRel(-1),
      'coverImageUrl':
          'https://images.unsplash.com/photo-1491841573634-28140fc7ced7?q=80&w=2000&auto=format&fit=crop',
    },
    {
      'id': 'room_6',
      'eventId': null,
      'title': 'Grace Encounter',
      'description': 'Weekly sharing and prayer.',
      'objective': 'Build community in Christ.',
      'roomType': 'worship',
      'visibility': 'public',
      'status': 'open',
      'startDate': nowRel(0),
      'endDate': nowRel(365),
      'creatorId': 'admin_4',
      'createdAt': nowRel(-10),
      'coverImageUrl':
          'https://images.unsplash.com/photo-1438234591033-f0664589d960?q=80&w=2000&auto=format&fit=crop',
    },
  ];

  static List<Map<String, dynamic>> get activities => [
    {
      'id': 'act_1',
      'eventId': 'evt_1',
      'title': 'Opening Ceremony: Encounter',
      'description': 'The launch event for Global Revival.',
      'activityType': 'worship',
      'locationName': 'Main Sanctuary & Online',
      'mapLink': 'https://maps.google.com/?q=jerusalem',
      'startDateTime': nowRel(-5, hours: 18),
      'endDateTime': nowRel(-5, hours: 21),
      'costType': 'free',
      'organizerContact': '+1 (555) 000-0001',
      'createdAt': nowRel(-10),
      'config': {
        'videoUrls': ['https://www.youtube.com/watch?v=dQw4w9WgXcQ'],
      },
    },
    {
      'id': 'act_2',
      'eventId': 'evt_1',
      'title': 'Morning Silence: Solitude',
      'description': 'Wait on the Lord in total silence.',
      'activityType': 'silence',
      'locationName': 'Prayer Garden',
      'mapLink': '',
      'startDateTime': nowRel(1, hours: 6),
      'endDateTime': nowRel(1, hours: 7),
      'costType': 'free',
      'organizerContact': '+1 (555) 000-0001',
      'createdAt': nowRel(-4),
    },
    {
      'id': 'act_3',
      'eventId': 'evt_1',
      'title': 'Community Fellowship Dinner',
      'description': 'A time to share and break bread.',
      'activityType': 'meeting',
      'locationName': 'Fellowship Hall',
      'mapLink': '',
      'startDateTime': nowRel(2, hours: 19),
      'endDateTime': nowRel(2, hours: 21),
      'costType': 'paid',
      'price': 15.0,
      'organizerContact': '+1 (555) 000-0002',
      'createdAt': nowRel(-4),
      'config': {
        'meetingObjectives': ['Build bonds', 'Share testimonies'],
        'dayName': 'Wednesday',
      },
    },
    {
      'id': 'act_4',
      'eventId': 'evt_2',
      'title': 'Proverbs 1: The Beginning of Knowledge',
      'description': 'Introductory study on the fear of the Lord.',
      'activityType': 'rhema',
      'locationName': 'Online Only',
      'mapLink': '',
      'startDateTime': nowRel(2, hours: 10),
      'endDateTime': nowRel(2, hours: 11),
      'costType': 'free',
      'organizerContact': '+1 (555) 000-0003',
      'createdAt': nowRel(-1),
      'config': {'scripture': 'Proverbs 1:1-7'},
    },
  ];

  static List<Map<String, dynamic>> get tasks => [
    {
      'id': 'task_1',
      'roomId': 'room_1',
      'title': 'Consecration Prayer',
      'description': 'Pray for 30 minutes focusing on holiness.',
      'taskType': 'prayer',
      'dayIndex': 1,
      'mandatory': true,
      'createdBy': 'user',
      'status': 'pending',
      'createdAt': nowRel(-5),
      'startHour': 0,
      'durationHours': 0.5,
      'prayerPoints': ['Repentance', 'Sanctification', 'Devotion'],
    },
    {
      'id': 'task_2',
      'roomId': 'room_2',
      'title': 'Profound Quietness',
      'description': 'Practice silence for 15 minutes before reading.',
      'taskType': 'silence',
      'dayIndex': 1,
      'mandatory': false,
      'createdBy': 'gemini',
      'status': 'completed',
      'createdAt': nowRel(-5),
      'durationMinutes': 15,
    },
  ];

  static List<Map<String, dynamic>> get messages => [
    {
      'id': 'm1',
      'chatId': 'room_1',
      'senderId': 'user_1',
      'senderName': 'Pastor John',
      'text': 'The presence of God is heavy here!',
      'createdAt': nowRel(-1, hours: 12),
    },
    {
      'id': 'm2',
      'chatId': 'room_1',
      'senderId': 'user_2',
      'senderName': 'Sarah M.',
      'text': 'Amen! Felt a breakthrough at 2am.',
      'createdAt': nowRel(-1, hours: 12, minutes: 5),
    },
  ];

  static List<Map<String, dynamic>> get governanceLogs => [
    {
      'id': 'log_1',
      'scope': 'room',
      'refId': 'room_1',
      'action': 'message_moderated',
      'executedBy': 'GEMINI',
      'targetUserId': 'user_2',
      'reason': 'Violated usage policy (harassment)',
      'createdAt': nowRel(-1),
      'metadata': {'originalObj': 'Bad message...'},
    },
    {
      'id': 'log_2',
      'scope': 'room',
      'refId': 'room_1',
      'action': 'topic_suggested',
      'executedBy': 'GEMINI',
      'targetUserId': null,
      'reason': 'Discussion stalled for 5 minutes',
      'createdAt': nowRel(0, minutes: -30),
      'metadata': {'suggestion': 'Focus on verse 5...'},
    },
  ];

  // User Profile Data
  static Map<String, dynamic> get userProfile => {
    'uid': 'user_offline',
    'displayName': 'Faithful Pilgrim',
    'avatarUrl': null,
    'spiritualInterests': [
      'Prayer',
      'Worship',
      'Bible Study',
      'Fasting',
      'Meditation',
    ],
    'stats': {
      'currentStreak': 7,
      'longestStreak': 14,
      'tasksCompleted': 42,
      'tasksCompletedThisWeek': 8,
      'hoursThisWeek': 12.5,
      'bibleChaptersRead': 23,
      'eventsJoined': 2,
      'roomsJoined': 2,
      'highlightsCreated': 5,
      'notesCreated': 3,
    },
    'preferences': {
      'darkMode': false,
      'notificationsEnabled': true,
      'language': 'en',
      'bibleVersion': 'KJV',
    },
    'createdAt': nowRel(-30),
    'lastActiveAt': nowRel(0),
  };

  // Activity History
  static List<Map<String, dynamic>> get activityHistory => [
    {
      'id': 'activity_1',
      'type': 'task_completed',
      'title': 'Completed Morning Prayer',
      'subtitle': 'Midnight Intercession',
      'timestamp': nowRel(0, hours: -17, minutes: -30),
      'metadata': {'taskId': 'task_1', 'roomId': 'room_1'},
    },
    {
      'id': 'activity_2',
      'type': 'bible_read',
      'title': 'Read Genesis 1-3',
      'subtitle': '3 chapters • 30 min',
      'timestamp': nowRel(0, hours: -17),
      'metadata': {
        'book': 'Genesis',
        'chapters': [1, 2, 3],
      },
    },
    {
      'id': 'activity_3',
      'type': 'note_created',
      'title': 'Added note to Notebook',
      'subtitle': 'Reflections on Genesis 1:1',
      'timestamp': nowRel(-1, hours: 21, minutes: 15),
      'metadata': {'noteId': 'note_1'},
    },
    {
      'id': 'activity_4',
      'type': 'room_joined',
      'title': 'Joined "Daily Rhema Exploration" Room',
      'subtitle': 'Global Revival 2026',
      'timestamp': nowRel(-1, hours: 20),
      'metadata': {'roomId': 'room_2', 'eventId': 'evt_1'},
    },
    {
      'id': 'activity_5',
      'type': 'event_registered',
      'title': 'Registered for Global Revival 2026',
      'subtitle': 'Starts in 5 days',
      'timestamp': nowRel(-6, hours: 14),
      'metadata': {'eventId': 'evt_1'},
    },
    {
      'id': 'activity_6',
      'type': 'highlight_created',
      'title': 'Highlighted Psalm 23:1',
      'subtitle': '"The Lord is my shepherd..."',
      'timestamp': nowRel(-2, hours: 19, minutes: 30),
      'metadata': {'verse': 'Psalm 23:1'},
    },
    {
      'id': 'activity_7',
      'type': 'task_completed',
      'title': 'Completed Profound Quietness',
      'subtitle': 'Daily Rhema Exploration',
      'timestamp': nowRel(-2, hours: 7),
      'metadata': {'taskId': 'task_2', 'roomId': 'room_2'},
    },
    {
      'id': 'activity_8',
      'type': 'bible_read',
      'title': 'Read Psalm 1-5',
      'subtitle': '5 chapters • 20 min',
      'timestamp': nowRel(-3, hours: 6, minutes: 30),
      'metadata': {
        'book': 'Psalms',
        'chapters': [1, 2, 3, 4, 5],
      },
    },
    {
      'id': 'activity_9',
      'type': 'room_joined',
      'title': 'Joined "Midnight Intercession" Room',
      'subtitle': 'Global Revival 2026',
      'timestamp': nowRel(-6, hours: 14, minutes: 30),
      'metadata': {'roomId': 'room_1', 'eventId': 'evt_1'},
    },
    {
      'id': 'activity_10',
      'type': 'task_completed',
      'title': 'Completed Scripture Meditation',
      'subtitle': 'Personal devotion',
      'timestamp': nowRel(-4, hours: 7, minutes: 15),
      'metadata': {'taskId': 'task_3'},
    },
  ];
}
